# Generated by Django 5.2.8 on 2025-11-21 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Solicitante')),
                ('cargo', models.CharField(help_text='Ej: Médico, Enfermera Jefe', max_length=100)),
                ('ubicacion', models.CharField(help_text='Ej: Urgencias, Sede Admin', max_length=100, verbose_name='Sede / Área')),
                ('descripcion', models.TextField(verbose_name='Descripción del Problema')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('categoria', models.CharField(choices=[('SIHOS', 'Falla en SIHOS'), ('EQUIPOS', 'Computador / Periféricos'), ('IMPRESORA', 'Impresoras / Toner'), ('RED', 'Internet / Conectividad'), ('OTRO', 'Otro Requerimiento')], default='OTRO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Asignar'), ('EN_PROCESO', 'En Revisión'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True, verbose_name='Solución Técnica')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico/Ing Asignado')),
            ],
        ),
    ]
